# Generated by Django 4.1.6 on 2023-02-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('frId', models.BigAutoField(help_text='Friendship ID', primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FUser',
            fields=[
                ('fuId', models.BigAutoField(help_text='FUser ID', primary_key=True, serialize=False)),
                ('frId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fUserPost', to='relation.friendship')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fUserPost', to=settings.AUTH_USER_MODEL, to_field='userName')),
            ],
        ),
    ]
