# Generated by Django 4.1.6 on 2023-03-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='userID',
            new_name='userId',
        ),
    ]
