# Generated by Django 4.1.6 on 2023-03-04 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0002_fuser_otheruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='otherUser',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.BigAutoField(help_text='Message ID', primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('frId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagePost', to='relation.friendship')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagePost', to=settings.AUTH_USER_MODEL, to_field='userName')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarmId', models.BigAutoField(help_text='Alarm ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('typeId', models.IntegerField()),
                ('isRead', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlarmPost', to=settings.AUTH_USER_MODEL, to_field='userName')),
            ],
        ),
    ]
