# Generated by Django 4.0.3 on 2023-01-11 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routineId', models.BigAutoField(help_text='Routine ID', primary_key=True, serialize=False)),
                ('keyDate', models.CharField(default=False, max_length=20)),
                ('text', models.TextField()),
                ('cycle', models.IntegerField()),
                ('startNum', models.IntegerField()),
                ('totalRoutine', models.IntegerField()),
                ('clearRoutine', models.IntegerField()),
                ('iconType', models.IntegerField(default=0)),
                ('topText', models.CharField(default=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DayRoutine',
            fields=[
                ('id', models.BigAutoField(help_text='DayRoutine ID', primary_key=True, serialize=False)),
                ('dayIndex', models.IntegerField()),
                ('clear', models.BooleanField(default=False)),
                ('routineId', models.ForeignKey(db_column='routineId', on_delete=django.db.models.deletion.CASCADE, related_name='dayRoutinePost', to='routine.routine')),
            ],
        ),
    ]
