# Generated by Django 4.0.3 on 2023-01-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('dayDataId', models.BigAutoField(help_text='DayDate ID', primary_key=True, serialize=False)),
                ('KeyDate', models.CharField(default=False, max_length=20)),
                ('day', models.IntegerField()),
                ('isSelected', models.BooleanField(default=False)),
                ('monthIndex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(help_text='Task ID', primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('isDone', models.BooleanField(default=False)),
                ('iconType', models.IntegerField(default=0)),
                ('level', models.IntegerField()),
                ('per', models.IntegerField(default=0)),
                ('dayDataId', models.ForeignKey(db_column='dayDataId', on_delete=django.db.models.deletion.CASCADE, related_name='taskPost', to='dayData.daydata')),
            ],
        ),
    ]
